# Generated by Django 5.1.3 on 2024-11-08 18:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_name', models.CharField(max_length=255, unique=True)),
                ('enterprise_type', models.CharField(max_length=255)),
                ('ownership', models.CharField(choices=[('Комунальна', 'Комунальна'), ('Приватна', 'Приватна'), ('Державна', 'Державна')], max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pollutant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollutant_name', models.CharField(max_length=255, unique=True)),
                ('chemical_formula', models.CharField(max_length=50)),
                ('GDK_avg_daily', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('danger_class', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('emission_per_year', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='app.enterprise')),
                ('pollutant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='app.pollutant')),
            ],
            options={
                'unique_together': {('year', 'enterprise', 'pollutant')},
            },
        ),
    ]
