# Generated by Django 5.1.3 on 2024-11-23 08:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_name', models.CharField(max_length=255, unique=True)),
                ('enterprise_type', models.CharField(max_length=255)),
                ('ownership', models.CharField(choices=[('Комунальна', 'Комунальна'), ('Приватна', 'Приватна'), ('Державна', 'Державна')], max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pollutant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollutant_name', models.CharField(max_length=255, unique=True)),
                ('atmosphere_tax', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('waterbody_tax', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('placement_tax', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('GDK_avg_daily', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('danger_class', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('emission_per_year', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='app.enterprise')),
                ('pollutant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='app.pollutant')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_type', models.CharField(choices=[('Atmosphere Tax', 'Податок за забруднення атмосфери'), ('Waterbody Tax', "Податок за забруднення водних об'єктів"), ('Placement Tax', 'Податок за розміщення відходів')], max_length=255)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.record')),
            ],
        ),
    ]
