# Generated by Django 5.1.3 on 2024-11-23 08:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.record')),
                ('tax_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_type', models.CharField(choices=[('Atmosphere Tax', 'Податок за забруднення атмосфери'), ('Waterbody Tax', "Податок за забруднення водних об'єктів"), ('Placement Tax', 'Податок за розміщення відходів')], max_length=255)),
            ],
            bases=('app.record',),
        ),
        migrations.AddField(
            model_name='pollutant',
            name='atmosphere_tax',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pollutant',
            name='placement_tax',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pollutant',
            name='waterbody_tax',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
