# Generated by Django 5.1.3 on 2024-11-23 14:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance_type', models.CharField(max_length=255)),
                ('danger_class', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('gdk', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('concentration', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('rfc', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sfi', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_risk', models.CharField(blank=True, max_length=50, null=True)),
                ('pollutant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pollutant')),
            ],
        ),
    ]
