# Generated by Django 5.1.3 on 2024-11-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tax_pollutant_atmosphere_tax_pollutant_placement_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollutant',
            name='chemical_formula',
        ),
    ]
